codecov:
  require_ci_to_pass: true
  allow_coverage_offsets: true

coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error

comment:
  layout: 'reach,diff,flags,tree'
  behavior: default
  require_changes: false

ignore:
  - '**/*.test.ts'
  - '**/*.test.js'
  - '**/*.spec.ts'
  - '**/*.spec.js'
  - '**/test/**'
  - '**/tests/**'
  - '**/coverage/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/node_modules/**'
  - '**/.vitepress/**'
  - '**/docs/**'
  - '**/examples/**'
  - '**/*.config.*'
  - '**/*.d.ts'
