coverage:
  precision: 2
  round: down
  range: 99...100

  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - '**/*.test.ts'
  - '**/*.test.js'
  - '**/*.spec.ts'
  - '**/*.spec.js'
  - '**/test/**'
  - '**/tests/**'
  - '**/coverage/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/node_modules/**'
  - '**/.vitepress/**'
  - '**/docs/**'
  - '**/examples/**'
  - '**/*.config.*'
  - '**/*.d.ts'
  - '**/*.test-d.ts'
  - '**/types.ts'

flags:
  color:
    paths:
      - packages/color/
    status:
      project:
        default:
          target: auto
  kit:
    paths:
      - packages/kit/
    status:
      project:
        default:
          target: 100%

  date:
    paths:
      - packages/date/
    status:
      project:
        default:
          target: auto

  biz:
    paths:
      - packages/biz/
    status:
      project:
        default:
          target: auto
