coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - '**/*.test.ts'
  - '**/*.test.js'
  - '**/*.spec.ts'
  - '**/*.spec.js'
  - '**/test/**'
  - '**/tests/**'
  - '**/coverage/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/node_modules/**'
  - '**/.vitepress/**'
  - '**/docs/**'
  - '**/examples/**'
  - '**/*.config.*'
  - '**/*.d.ts'

flags:
  color:
    paths:
      - packages/color/
  kit:
    paths:
      - packages/kit/
  date:
    paths:
      - packages/date/
