packages:
  - playground
  - docs
  - packages/*
  - examples/*
  - internal/*

ignoreWorkspaceRootCheck: true
shellEmulator: true

catalog:
  '@antfu/eslint-config': ^5.4.1
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.7
  '@commitlint/cli': ^20.1.0
  '@commitlint/config-conventional': ^20.0.0
  '@iconify-json/svg-spinners': ^1.2.4
  '@shikijs/vitepress-twoslash': 3.15.0
  '@types/culori': ^4.0.1
  '@types/node': ^24.10.0
  '@unocss/reset': ^66.5.5
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  '@vueuse/core': ^13.9.0
  chokidar: ^4.0.3
  commitlint-plugin-function-rules: ^4.1.1
  culori: ^4.0.2
  cz-git: ^1.12.0
  czg: ^1.12.0
  date-fns: ^4.1.0
  eslint: ^9.39.1
  eslint-plugin-format: ^1.0.2
  fast-glob: ^3.3.3
  floating-vue: ^5.2.2
  lefthook: ^1.13.6
  pinia: ^3.0.4
  pnpm: ^10.21.0
  tinyexec: ^1.0.2
  tsdown: ^0.16.1
  tsx: ^4.20.6
  turbo: ^2.6.0
  typescript: ^5.9.3
  unocss: ^66.5.5
  unplugin-vue-components: ^30.0.0
  vite: ^7.2.2
  vite-tsconfig-paths: ^5.1.4
  vitepress: 2.0.0-alpha.12
  vitepress-plugin-group-icons: ^1.6.5
  vitest: ^3.2.4
  vitest-package-exports: ^0.1.1
  vue: ^3.5.24
  yaml: ^2.8.1
onlyBuiltDependencies:
  - esbuild
  - lefthook
peerDependencyRules:
  allowedVersions:
    eslint: '*'
