packages:
  - playground
  - docs
  - packages/*
  - examples/*
  - internal/*
catalog:
  '@antfu/eslint-config': ^5.2.1
  '@antfu/utils': ^9.2.0
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.6
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@iconify-json/svg-spinners': ^1.2.4
  '@shikijs/vitepress-twoslash': ^3.12.1
  '@types/node': ^24.3.0
  '@unocss/reset': ^66.5.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  '@vueuse/core': ^13.9.0
  bumpp: ^10.2.3
  chokidar: ^4.0.3
  commitlint-plugin-function-rules: ^4.0.2
  culori: ^4.0.2
  cz-git: ^1.12.0
  czg: ^1.12.0
  esbuild: ^0.25.9
  eslint: ^9.34.0
  eslint-plugin-format: ^1.0.1
  fast-glob: ^3.3.3
  floating-vue: ^5.2.2
  lefthook: ^1.12.3
  pinia: ^3.0.3
  pnpm: ^10.15.1
  tinyexec: ^1.0.1
  tsx: ^4.20.5
  turbo: ^2.5.6
  typescript: ^5.9.2
  unbuild: ^3.6.1
  unocss: ^66.5.0
  unplugin-vue-components: ^29.0.0
  vite: ^7.1.4
  vite-tsconfig-paths: ^5.1.4
  vitepress: 2.0.0-alpha.12
  vitepress-plugin-group-icons: ^1.6.3
  vitest: ^3.2.4
  vitest-package-exports: ^0.1.1
  vue: ^3.5.21
  yaml: ^2.8.1
