packages:
  - playground
  - docs
  - packages/*
  - examples/*
  - internal/*

catalog:
  '@antfu/eslint-config': ^6.7.3
  '@changesets/changelog-github': ^0.5.2
  '@changesets/cli': ^2.29.8
  '@commitlint/cli': ^20.3.1
  '@commitlint/config-conventional': ^20.3.1
  '@iconify-json/svg-spinners': ^1.2.4
  '@shikijs/vitepress-twoslash': 3.13.0
  '@types/culori': ^4.0.1
  '@types/node': ^24.10.7
  '@types/qs': ^6.14.0
  '@unocss/reset': ^66.5.12
  '@vitest/coverage-v8': ^4.0.16
  '@vitest/ui': ^4.0.16
  '@vueuse/core': ^13.9.0
  chokidar: ^4.0.3
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commitlint-plugin-function-rules: ^4.3.0
  culori: ^4.0.2
  cz-git: ^1.12.0
  czg: ^1.12.0
  date-fns: ^4.1.0
  eslint: ^9.39.2
  eslint-plugin-format: ^1.2.0
  fast-glob: ^3.3.3
  floating-vue: ^5.2.2
  lefthook: ^2.0.13
  mermaid: ^11.12.2
  pinia: ^3.0.4
  pnpm: ^10.28.0
  qs: ^6.14.1
  tailwind-merge: ^3.4.0
  tinyexec: ^1.0.2
  tsdown: ^0.19.0
  tsx: ^4.21.0
  turbo: ^2.7.3
  typescript: ^5.9.3
  unocss: ^66.5.12
  unplugin-vue-components: ^30.0.0
  vite: ^7.3.1
  vite-tsconfig-paths: ^5.1.4
  vitepress: 2.0.0-alpha.12
  vitepress-plugin-group-icons: ^1.6.5
  vitepress-plugin-mermaid: ^2.0.17
  vitest: ^4.0.16
  vitest-package-exports: ^1.1.2
  vue: ^3.5.26
  yaml: ^2.8.2

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - lefthook

peerDependencyRules:
  allowedVersions:
    eslint: '*'

shellEmulator: true
