packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog:
  '@antfu/eslint-config': ^5.0.0
  '@antfu/utils': ^9.2.0
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@iconify-json/svg-spinners': ^1.2.2
  '@shikijs/vitepress-twoslash': ^3.8.1
  '@types/node': ^24.1.0
  '@unocss/reset': ^66.3.3
  '@vitejs/plugin-vue': ^6.0.1
  '@vueuse/core': ^13.6.0
  bumpp: ^10.2.1
  commitlint-plugin-function-rules: ^4.0.2
  cz-git: ^1.12.0
  czg: ^1.11.1
  esbuild: ^0.25.8
  eslint: ^9.32.0
  eslint-plugin-format: ^1.0.1
  floating-vue: ^5.2.2
  lefthook: ^1.12.2
  pinia: ^3.0.3
  pnpm: ^10.13.1
  tsx: ^4.20.3
  turbo: ^2.5.5
  typescript: ^5.8.3
  unbuild: ^3.6.0
  unocss: ^66.3.3
  unplugin-vue-components: ^28.8.0
  vite: ^7.0.6
  vite-tsconfig-paths: ^5.1.4
  vitepress: 2.0.0-alpha.9
  vitepress-plugin-group-icons: ^1.6.1
  vitest: ^3.2.4
  vue: ^3.5.18
