packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^5.2.1
  '@antfu/utils': ^9.2.0
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@iconify-json/svg-spinners': ^1.2.4
  '@shikijs/vitepress-twoslash': ^3.9.2
  '@types/node': ^24.2.1
  '@unocss/reset': ^66.4.2
  '@vitejs/plugin-vue': ^6.0.1
  '@vitest/coverage-v8': ^3.2.4
  '@vitest/ui': ^3.2.4
  '@vueuse/core': ^13.6.0
  bumpp: ^10.2.3
  chokidar: ^4.0.3
  commitlint-plugin-function-rules: ^4.0.2
  cz-git: ^1.12.0
  czg: ^1.12.0
  esbuild: ^0.25.9
  eslint: ^9.33.0
  eslint-plugin-format: ^1.0.1
  fast-glob: ^3.3.3
  floating-vue: ^5.2.2
  lefthook: ^1.12.3
  pinia: ^3.0.3
  pnpm: ^10.14.0
  tinyexec: ^1.0.1
  tsx: ^4.20.4
  turbo: ^2.5.5
  typescript: ^5.9.2
  unbuild: ^3.6.0
  unocss: ^66.4.2
  unplugin-vue-components: ^29.0.0
  vite: ^7.1.2
  vite-tsconfig-paths: ^5.1.4
  vitepress: 2.0.0-alpha.10
  vitepress-plugin-group-icons: ^1.6.3
  vitest: ^3.2.4
  vitest-package-exports: ^0.1.1
  vue: ^3.5.18
  yaml: ^2.8.1
