export * from './is-alnum'
export * from './is-alpha'
export * from './is-circular'
export * from './is-digit'
export * from './is-email'
export * from './is-firefox'
export * from './is-phone'
export * from './is-safari'
