name: Delete Workflow Runs

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 7
          keep_minimum_runs: 0
