name: Create Version PR

on:
  push:
    branches:
      - main
    paths:
      - '.changeset/**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token for Bot
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          installation-id: ${{ secrets.BOT_INSTALLATION_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          token: ${{ steps.generate_token.outputs.token }} # 使用动态生成的 token
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Version Files
        run: pnpm changeset version

      - name: Create Pull Request for Versioning
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate_token.outputs.token }} # 使用动态生成的 token
          commit-message: 'release: version packages'
          title: 'Release: Version Packages'
          body: |
            An automated PR to version packages...
          branch: chore/changeset-release
          author: 'esdora-bot[bot] <158852345+esdora-bot[bot]@users.noreply.github.com>' # 你的 App 的唯一 ID
          committer: 'esdora-bot[bot] <158852345+esdora-bot[bot]@users.noreply.github.com>'
          delete-branch: true
