name: Create Version PR

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Generate Token for Bot
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          installation-id: ${{ secrets.BOT_INSTALLATION_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Version Files
        run: pnpm changeset version
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Generate PR Body
        id: generate_pr_body
        run: |
          set -e
          BODY_FILE=pr_body.md
          echo -e "An automated PR to version packages. This was generated by the \`Create Version PR\` workflow.\\n" > $BODY_FILE
          echo -e "Merging this PR will trigger the release workflow to publish packages to npm.\\n\\n---\\n\\n" >> $BODY_FILE
          for file in $(git status --porcelain | grep 'packages/.*/CHANGELOG.md' | awk '{print $2}'); do
            LATEST_ENTRY=$(awk 'BEGIN{p=0} /^## / {p++} p < 2' "$file")
            echo "$LATEST_ENTRY" >> $BODY_FILE
            echo "" >> $BODY_FILE
          done
          echo "body_path=$BODY_FILE" >> $GITHUB_OUTPUT

      - name: Create Pull Request for Versioning
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: 'chore(release): publish new version'
          title: 'chore(release): publish new version'
          body-path: ${{ steps.generate_pr_body.outputs.body_path }}
          branch: chore/changeset-release
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          delete-branch: true
